stages:
  - test
  - build
  - delpoyToAws
  
test:
  stage: test
  image: python:3
  script:
    - echo "teste"

build:
  image: docker
  only:
    - main
  services:
    - docker:dind
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:backAPI" .
    - docker push "$CI_REGISTRY_IMAGE:backAPI"

delpoyToAws:
  stage: delpoyToAws
  image: alpine
  only:
    - main
  variables:
    SERVER: $SERVER_IP
    PORT: $PORT
  script:
    - apk add openssh
    - apk add bash
    - mkdir ~/.ssh
    - echo "$SSH_KNOWN_HOSTS_AWS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    # add ssh key stored in SSH_PRIVATE_KEY variable to the agent store
    - eval $(ssh-agent -s)
    - bash -c 'ssh-add <(echo "$SSH_PRIVATE_KEY_AWS")'
    # log into Docker registry
    #- ssh deployer@$SERVER "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com"
    - ssh ubuntu@$SERVER "echo $CI_BUILD_TOKEN | docker login --username gitlab-ci-token --password-stdin registry.gitlab.com"
    # stop container, remove image.
    - ssh ubuntu@$SERVER "docker container stop backAPI" || true
    - ssh ubuntu@$SERVER "docker container rm backAPI" || true
    - ssh ubuntu@$SERVER "docker image rm ${CI_REGISTRY_IMAGE}:backAPI" || true
    # start new container
    - ssh ubuntu@$SERVER "docker container run --name backAPI -p $PORT:8000 -d ${CI_REGISTRY_IMAGE}:backAPI"
