version: "3.9" 
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db